### ISSUE TITLE
null values in numTests

### ISSUE THREAD

**Issue by volanslp** [yahoo/covid-19-data#16]
As of 4/28, I went through all tsv or json files in master branch and found numTests to be null. I have seen non-null numTests values in other sources (e.g Johns Hopkins) and want to check if the sources Yahoo pulled together is indicated all null numTests values.

**Comment by asafary** [comment]
Thank you for commenting.

As of now (2020-04-28) we have decided that the information we receive for `numTests` is not reliable for many regions.
There is no consensus regarding how to count tests.
Some regions count the number of tests administered whereas others count the number of tests analyzed in the lab. I addition most regions do not report test numbers at all.

Due to the inconsistency of this data, we have decided to replace the field with a different metric which is more reliable.

We will post an issue here to update on the upcoming schema change

**Comment by asafary** [comment]
`numTests` removed in #19
